var tinyMCEImageList = new Array(
['   images: bullet.gif','/images/bullet.gif'],
['   images: cms-logo-big.png','/images/cms-logo-big.png'],
['   images: imagenotfound.jpg','/images/imagenotfound.jpg'],
['   images: cms-logo-small.png','/images/cms-logo-small.png'],
['   images: photonotfound.jpg','/images/photonotfound.jpg'],
['     news: bugs.gif','/images/news/bugs.gif'],
['     news: software.gif','/images/news/software.gif'],
['     news: movies.gif','/images/news/movies.gif'],
['     news: themes.gif','/images/news/themes.gif'],
['     news: downloads.gif','/images/news/downloads.gif'],
['     news: graphics.gif','/images/news/graphics.gif'],
['     news: journal.gif','/images/news/journal.gif'],
['     news: games.gif','/images/news/games.gif'],
['     news: mods.gif','/images/news/mods.gif'],
['     news: news.gif','/images/news/news.gif'],
['     news: windows.gif','/images/news/windows.gif'],
['     news: security.gif','/images/news/security.gif'],
['     news: hardware.gif','/images/news/hardware.gif'],
['     news: network.gif','/images/news/network.gif'],
['     news: members.gif','/images/news/members.gif'],
['downloads: software.gif','/images/download_cats/software.gif'],
['downloads: themes.gif','/images/download_cats/themes.gif'],
['downloads: downloads.gif','/images/download_cats/downloads.gif'],
['downloads: mods.gif','/images/download_cats/mods.gif'],
['downloads: security.gif','/images/download_cats/security.gif']);
